apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db
  labels:
    {{- include "dfir-iris.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.database.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.database.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-shared
  labels:
    {{- include "dfir-iris.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.shared.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.shared.size }}
