{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dfir-iris.secretName" . }}
  labels:
    {{- include "dfir-iris.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRES_ADMIN_PASSWORD: {{ .Values.secrets.postgresAdminPassword | quote }}
  IRIS_SECRET_KEY: {{ .Values.secrets.irisSecretKey | quote }}
  IRIS_SECURITY_PASSWORD_SALT: {{ .Values.secrets.irisSecurityPasswordSalt | quote }}
  IRIS_ADM_PASSWORD: {{ .Values.secrets.irisAdminPassword | quote }}
{{- end }}
