apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    {{- include "dfir-iris.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "dfir-iris.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - ./wait-for-iriswebapp.sh
            - {{ printf "%s:8000" .Release.Name | quote }}
            - ./iris-entrypoint.sh
            - iris-worker
          env:
            - name: LOG_LEVEL
              value: {{ .Values.iris.logLevel | quote }}
            - name: DOCKERIZED
              value: "1"
            - name: IRIS_WORKER
              value: "1"
            - name: POSTGRES_USER
              value: {{ .Values.iris.postgresUser | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dfir-iris.secretName" . }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_ADMIN_USER
              value: {{ .Values.iris.postgresAdminUser | quote }}
            - name: POSTGRES_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dfir-iris.secretName" . }}
                  key: POSTGRES_ADMIN_PASSWORD
            - name: POSTGRES_DB
              value: {{ .Values.iris.postgresDatabase | quote }}
            - name: POSTGRES_SERVER
              value: {{ printf "%s-db" .Release.Name | quote }}
            - name: POSTGRES_PORT
              value: "5432"
            - name: CELERY_BROKER
              value: {{ printf "amqp://%s-rabbitmq" .Release.Name | quote }}
            - name: IRIS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "dfir-iris.secretName" . }}
                  key: IRIS_SECRET_KEY
            - name: IRIS_SECURITY_PASSWORD_SALT
              valueFrom:
                secretKeyRef:
                  name: {{ include "dfir-iris.secretName" . }}
                  key: IRIS_SECURITY_PASSWORD_SALT
          volumeMounts:
            - name: shared
              mountPath: /home/iris/downloads
              subPath: downloads
            - name: shared
              mountPath: /home/iris/user_templates
              subPath: user_templates
            - name: shared
              mountPath: /home/iris/server_data
              subPath: server_data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-shared
